apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: news-analyzer
resources:
  - ops-rbac.yaml
  - ops-configmap.yaml
  - ops-health-cronjob.yaml
  - ops-cleanup-cronjob.yaml
  # ops-deployer-job.yaml is optional; apply on demand
