apiVersion: v1
kind: Namespace
metadata:
  name: news-analyzer
  labels:
    app: news-analyzer
    purpose: automated-news-processing
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: news-analyzer-quota
  namespace: news-analyzer
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    count/cronjobs.batch: "5"
    count/jobs.batch: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: news-analyzer-limits
  namespace: news-analyzer
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container