apiVersion: v1
kind: ResourceQuota
metadata:
  name: news-analyzer-quota
  namespace: news-analyzer
spec:
  hard:
    requests.cpu: "5"
    requests.memory: "10Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    persistentvolumeclaims: "10"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"