# Secrets template for news analyzer
# Copy this file to secrets.yaml and replace placeholder values
# DO NOT commit secrets.yaml to version control

apiVersion: v1
kind: Secret
metadata:
  name: news-analyzer-secrets
  namespace: news-analyzer
  labels:
    app: news-analyzer
type: Opaque
stringData:
  # E-edition credentials
  EEDITION_USER: "your_email@example.com"
  EEDITION_PASS: "your_password"
  
  # SmartProxy credentials (from athena-scraper)
  SMARTPROXY_USER: "spua66m4sy"
  SMARTPROXY_PASS: "7h4nhZm69jvME~mslX"
  
  # Database connection
  DATABASE_URL: "postgresql://news_analyzer:changeme-strong-password-here@postgres-service:5432/news_analyzer"
  
  # MinIO credentials (should match minio-creds-secret)
  MINIO_ACCESS_KEY: "news-analyzer"
  MINIO_SECRET_KEY: "changeme-strong-secret-key"
  
  # OpenAI API key
  OPENAI_API_KEY: "sk-your_openai_api_key_here"
  
  # Ntfy credentials (optional, if you want auth)
  NTFY_TOKEN: ""  # Leave empty if not using auth
  
  # Optional: Slack webhook URL
  SLACK_WEBHOOK_URL: ""  # Leave empty if not using Slack

---
# Instructions for setting up secrets:
#
# 1. Copy this file: cp k8s/secrets-template.yaml k8s/secrets.yaml
# 2. Edit k8s/secrets.yaml with your actual credentials
# 3. Apply the secrets: kubectl apply -f k8s/secrets.yaml
# 4. Add k8s/secrets.yaml to .gitignore to prevent accidental commits
#
# Required credentials to obtain:
# 
# E-edition credentials:
# - Sign up for an account at swvatoday.com
# - Use your email and password
#
# SmartProxy credentials:
# - Already provided from athena-scraper project
# - These are valid proxy credentials
#
# Database:
# - Will be auto-created by the postgres deployment
# - Update the password in postgres-secret if needed
# - Make sure passwords match between postgres-secret and this file
#
# MinIO:
# - Will be auto-created by the MinIO tenant
# - Update credentials in minio-creds-secret if needed
# - Make sure credentials match between minio-creds-secret and this file
#
# OpenAI:
# - Sign up at openai.com
# - Create API key in dashboard
# - Ensure you have credits/billing set up
#
# Ntfy (optional auth):
# - After deploying ntfy, create a user: 
#   kubectl exec -it deployment/ntfy -n news-analyzer -- ntfy user add news-analyzer
# - Generate a token:
#   kubectl exec -it deployment/ntfy -n news-analyzer -- ntfy token add news-analyzer
#
# Slack (optional):
# - Create Slack app in your workspace
# - Enable incoming webhooks
# - Get webhook URL for your channel

---
# For iPhone Push Notifications via ntfy:
#
# 1. Download the ntfy app from the App Store
# 2. In the app settings, change the default server to your ntfy URL
#    (e.g., https://ntfy.yourdomain.com)
# 3. Subscribe to the "news-digest" topic
# 4. Enable notifications for the app in iOS settings
#
# The ntfy configuration is set up to proxy iOS notifications through
# the public ntfy.sh server, which handles the Apple Push Notification
# Service (APNS) integration. Your data stays private on your server.