# This is a template file. Copy to secrets.yaml and fill in actual values
apiVersion: v1
kind: Secret
metadata:
  name: news-analyzer-secrets
  namespace: news-analyzer
  labels:
    app: news-analyzer
type: Opaque
stringData:
  # E-edition credentials
  EEDITION_USER: "your_email@example.com"
  EEDITION_PASS: "your_password"
  
  # SmartProxy credentials (already configured with working credentials)
  SMARTPROXY_USER: "spua66m4sy"
  SMARTPROXY_PASS: "7h4nhZm69jvME~mslX"
  
  # OpenAI API key
  OPENAI_API_KEY: "sk-your-openai-api-key-here"
  
  # MinIO credentials
  MINIO_ACCESS_KEY: "your-minio-access-key"
  MINIO_SECRET_KEY: "your-minio-secret-key"
  
  # Database credentials
  DATABASE_USER: "news_analyzer"
  DATABASE_PASSWORD: "your-database-password"
  DATABASE_URL: "postgresql://news_analyzer:your-database-password@postgres.lan:5432/news_analyzer"
  
  # Email credentials (SendGrid)
  EMAIL_API_KEY: "your-sendgrid-api-key"
  EMAIL_TO: "your-email@example.com"
  
  # Slack webhook (optional)
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"