# Secrets template for news analyzer
# Copy this file to secrets.yaml and replace placeholder values
# DO NOT commit secrets.yaml to version control

apiVersion: v1
kind: Secret
metadata:
  name: news-analyzer-secrets
  namespace: news-analyzer
  labels:
    app: news-analyzer
type: Opaque
stringData:
  # E-edition credentials
  EEDITION_USER: "your_email@example.com"
  EEDITION_PASS: "your_password"
  
  # SmartProxy credentials (from athena-scraper)
  SMARTPROXY_USER: "spua66m4sy"
  SMARTPROXY_PASS: "7h4nhZm69jvME~mslX"
  
  # Database URL
  DATABASE_URL: "postgresql://user:password@postgres.lan:5432/news_analyzer"
  
  # MinIO credentials
  MINIO_ACCESS_KEY: "your_minio_access_key"
  MINIO_SECRET_KEY: "your_minio_secret_key"
  
  # OpenAI API key
  OPENAI_API_KEY: "sk-your_openai_api_key_here"
  
  # Email credentials (SendGrid)
  EMAIL_API_KEY: "SG.your_sendgrid_api_key_here"
  EMAIL_TO: "recipient@example.com"
  
  # Optional: Slack webhook URL
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

---
# Instructions for setting up secrets:
#
# 1. Copy this file: cp k8s/secrets-template.yaml k8s/secrets.yaml
# 2. Edit k8s/secrets.yaml with your actual credentials
# 3. Apply the secrets: kubectl apply -f k8s/secrets.yaml
# 4. Add k8s/secrets.yaml to .gitignore to prevent accidental commits
#
# Required credentials to obtain:
# 
# E-edition credentials:
# - Sign up for an account at swvatoday.com
# - Use your email and password
#
# SmartProxy credentials:
# - Already provided from athena-scraper project
# - These are valid proxy credentials
#
# Database:
# - Set up PostgreSQL database
# - Create database named 'news_analyzer'
# - Update DATABASE_URL with correct credentials
#
# MinIO:
# - Set up MinIO instance (or use existing one)
# - Create access key and secret key
# - Ensure bucket 'news-cache' exists or will be auto-created
#
# OpenAI:
# - Sign up at openai.com
# - Create API key in dashboard
# - Ensure you have credits/billing set up
#
# SendGrid (for email):
# - Sign up at sendgrid.com
# - Create API key with Mail Send permissions
# - Verify sender identity
#
# Slack (optional):
# - Create Slack app in your workspace
# - Enable incoming webhooks
# - Get webhook URL for your channel