name: CI/CD Pipeline (disabled)
on:
  # Disabled automatic triggers; keep manual dispatch only
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/news-analyzer

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [scraper, extractor, notifier, summarizer]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ${{ matrix.component }}/.venv
        key: ${{ runner.os }}-poetry-${{ matrix.component }}-${{ hashFiles(format('{0}/pyproject.toml', matrix.component)) }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ matrix.component }}-
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.component }}
        poetry install --with dev --no-interaction
    
    - name: Run linting
      run: |
        cd ${{ matrix.component }}
        # Install linting tools if not present
        poetry run pip install ruff mypy --quiet
        poetry run ruff check . || echo "Ruff not configured or found issues"
        poetry run mypy . --ignore-missing-imports || echo "MyPy not configured or found issues"
      continue-on-error: true
    
    - name: Run tests
      run: |
        cd ${{ matrix.component }}
        # Check if tests exist
        if [ -d "tests" ] || ls test_*.py 2>/dev/null || ls *_test.py 2>/dev/null; then
          poetry run pytest tests/ -v --cov=${{ matrix.component }} --cov-report=xml || echo "Tests failed or not configured"
        else
          echo "No tests found for ${{ matrix.component }}"
        fi
      continue-on-error: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        file: ./${{ matrix.component }}/coverage.xml
        flags: ${{ matrix.component }}
        name: ${{ matrix.component }}-coverage
      continue-on-error: true

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - component: scraper
            dockerfile: scraper/Dockerfile
            context: scraper
          - component: extractor
            dockerfile: extractor/Dockerfile
            context: extractor
          - component: notifier
            dockerfile: notifier/Dockerfile
            context: notifier
          - component: summarizer
            dockerfile: summarizer/Dockerfile
            context: summarizer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU (multi-arch)
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-${{ matrix.component }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    
    steps:
    - uses: actions/checkout@v4

    - name: Check for kubeconfig secret
      id: kubecheck
      run: |
        if [ -n "${{ secrets.KUBECONFIG_B64 }}" ] || [ -n "${{ secrets.KUBECONFIG }}" ]; then
          echo "has_kube=true" >> $GITHUB_OUTPUT
        else
          echo "has_kube=false" >> $GITHUB_OUTPUT
        fi

    - name: Install kubectl
      if: steps.kubecheck.outputs.has_kube == 'true'
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup kubeconfig
      if: steps.kubecheck.outputs.has_kube == 'true'
      run: |
        mkdir -p $HOME/.kube
        if [ -n "${{ secrets.KUBECONFIG_B64 }}" ]; then
          echo "Using base64-encoded kubeconfig from secrets"
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
        else
          echo "Using plaintext kubeconfig from secrets"
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        fi
        chmod 600 $HOME/.kube/config
    
    - name: Update Kubernetes deployments
      if: steps.kubecheck.outputs.has_kube == 'true'
      run: |
        # Update image tags in deployments and cronjobs
        kubectl set image cronjob/news-analyzer-scraper scraper=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-scraper:main-${{ github.sha }} -n news-analyzer || true
        kubectl set image deployment/summarizer summarizer=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-summarizer:main-${{ github.sha }} -n news-analyzer || true
        kubectl set image cronjob/news-analyzer-notifier notifier=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-notifier:main-${{ github.sha }} -n news-analyzer || true
        kubectl set image cronjob/news-analyzer-extractor extractor=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-extractor:main-${{ github.sha }} -n news-analyzer || true
        
        # Apply any configuration changes
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secrets.yaml || true
        
        # Check rollout status for deployments only
        kubectl rollout status deployment/summarizer -n news-analyzer --timeout=5m || true
        
        # Restart cronjobs to pick up new images by creating manual jobs
        kubectl create job --from=cronjob/news-analyzer-scraper scraper-manual-$(date +%s) -n news-analyzer || true
        kubectl create job --from=cronjob/news-analyzer-extractor extractor-manual-$(date +%s) -n news-analyzer || true

    - name: Skip deploy (no kubeconfig provided)
      if: steps.kubecheck.outputs.has_kube != 'true'
      run: echo "Kubeconfig secret not provided; skipping deploy to Kubernetes."

  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    strategy:
      matrix:
        component: [scraper, extractor, notifier, summarizer]
    
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-${{ matrix.component }}:main-${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results-${{ matrix.component }}.sarif'
      continue-on-error: true
    
    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results-${{ matrix.component }}.sarif'
      continue-on-error: true

  notify-status:
    needs: [lint-and-test, build-and-push, deploy-to-k8s]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Send notification
      run: |
        # Determine overall status across required jobs
        STATUS="success"
        if [ "${{ needs.lint-and-test.result }}" = "failure" ] || \
           [ "${{ needs.build-and-push.result }}" = "failure" ] || \
           [ "${{ needs.deploy-to-k8s.result }}" = "failure" ]; then
          STATUS="failure"
        fi

        curl -d "CI/CD Pipeline ${STATUS} for ${{ github.repository }} - ${{ github.ref_name }} - ${{ github.sha }}" \
          -H "Title: News Analyzer CI/CD" \
          -H "Priority: 3" \
          -H "Tags: ${STATUS}" \
          http://ntfy.news-analyzer.svc.cluster.local/news-analyzer-ci || true
