name: Dependency Update (manual)

on:
  # Disabled schedule; keep manual dispatch only
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        component: [root, scraper, extractor, notifier, summarizer]
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    
    - name: Update dependencies
      run: |
        if [ "${{ matrix.component }}" = "root" ]; then
          echo "Updating root dependencies..."
          poetry update --no-interaction
        else
          echo "Updating ${{ matrix.component }} dependencies..."
          cd ${{ matrix.component }}
          poetry update --no-interaction
        fi
    
    - name: Check for changes
      id: check_changes
      run: |
        # Check if any pyproject.toml files have changed
        if git diff --quiet HEAD -- '**/pyproject.toml' pyproject.toml; then
          echo "No dependency changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Dependency changes detected"
          echo "changes=true" >> $GITHUB_OUTPUT
          git diff --name-only HEAD -- '**/pyproject.toml' pyproject.toml
        fi
    
    - name: Create Pull Request
      if: steps.check_changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(${{ matrix.component }}): update dependencies'
        title: 'chore(${{ matrix.component }}): Update dependencies'
        body: |
          ## Automated Dependency Update

          This PR updates the dependencies for the ${{ matrix.component }} component.

          ### Changes
          - Updated dependencies to latest compatible versions
          - All dependency updates follow semantic versioning constraints

          ### Testing
          - [ ] CI tests pass
          - [ ] Manual testing completed
          - [ ] No breaking changes identified

          Please review the dependency changes and merge if all tests pass.
        branch: dependency-update/${{ matrix.component }}-${{ github.run_number }}
        delete-branch: true
        labels: |
          dependencies
          automated
          ${{ matrix.component }}
